// Re-export shim for backward compatibility — all state APIs now live in @project/core
export type {
	ProjectContext,
	RecentFileEntry,
	FileEntry,
	FileStore,
	UseFileResult,
	UseFileStringResult,
	SeverityLevel,
	ValidationResult,
	ValidatorFn,
	ValidatorRegistration,
	ValidatorRegistry,
	ValidationSummary,
	ValidationStore,
} from "@project/core";
export {
	useAppStore,
	useProjectSession,
	useCurrentProject,
	TreeSnapshot,
	useFileStore,
	isDirty,
	isError,
	getEntry,
	selectEntry,
	selectIsSaving,
	WriteQueue,
	getWriteQueue,
	disposeWriteQueue,
	useFile,
	useFileString,
	severityLabel,
	isErrorOrWarning,
	findUnknownProperties,
	createValidatorRegistry,
	createValidationRunner,
	useValidationStore,
	createDefaultValidators,
	ValidationResults,
} from "@project/core";
