import * as v from "valibot";
import { Interps, MindustryHexColorSchema, SoundHjsonSchema, type SchemaFn } from "./base";
import { EffectFieldSchema } from "./effect";
import { PartHjsonSchema } from "./part";
import { ShootPatternHjsonSchema } from "./shoot-pattern";
import { StatusFieldSchema } from "./status";
import { LiquidFieldSchema } from "./liquid";
import { UnitFieldSchema } from "./unit";

const metadata = { type: "bullet" };

export const bulletTypes = [
	"ArtilleryBulletType",
	"BasicBulletType",
	"BombBulletType",
	"BulletType",
	"ContinuousBulletType",
	"ContinuousFlameBulletType",
	"ContinuousLaserBulletType",
	"EmpBulletType",
	"EmptyBulletType",
	"ExplosionBulletType",
	"FireBulletType",
	"FlakBulletType",
	"InterceptorBulletType",
	"LaserBoltBulletType",
	"LaserBulletType",
	"LightningBulletType",
	"LiquidBulletType",
	"MassDriverBolt",
	"MissileBulletType",
	"MultiBulletType",
	"PointBulletType",
	"PointLaserBulletType",
	"RailBulletType",
	"SapBulletType",
	"ShrapnelBulletType",
	"SpaceLiquidBulletType",
] as const;

export type BulletClass = (typeof bulletTypes)[number];

type BulletObjectSchema = v.ObjectSchema<v.ObjectEntries, v.ErrorMessage<v.ObjectIssue> | undefined>;

const createBulletBaseObjectSchema: SchemaFn<v.ObjectSchema<v.ObjectEntries, v.ErrorMessage<v.ObjectIssue> | undefined>> = (context) => {
	return v.object({
		type: v.picklist(bulletTypes),
		lifetime: v.optional(v.number(), 40),
		lifeScaleRandMin: v.optional(v.number(), 1),
		lifeScaleRandMax: v.optional(v.number(), 1),
		speed: v.optional(v.number(), 1),
		velocityScaleRandMin: v.optional(v.number(), 1),
		velocityScaleRandMax: v.optional(v.number(), 1),
		damage: v.optional(v.number(), 1),
		hitSize: v.optional(v.number(), 4),
		drawSize: v.optional(v.number(), 40),
		angleOffset: v.optional(v.number(), 0),
		randomAngleOffset: v.optional(v.number(), 0),
		drag: v.optional(v.number(), 0),
		accel: v.optional(v.number(), 0),
		pierce: v.optional(v.boolean(), false),
		pierceBuilding: v.optional(v.boolean(), false),
		pierceCap: v.optional(v.number(), -1),
		pierceDamageFactor: v.optional(v.number(), 0),
		maxDamageFraction: v.optional(v.number(), -1),
		removeAfterPierce: v.optional(v.boolean(), true),
		laserAbsorb: v.optional(v.boolean(), true),
		optimalLifeFract: v.optional(v.number(), 0),
		layer: v.optional(v.number()),
		hitEffect: v.optional(EffectFieldSchema(context)),
		despawnEffect: v.optional(EffectFieldSchema(context)),
		shootEffect: v.optional(EffectFieldSchema(context)),
		shootPattern: v.optional(ShootPatternHjsonSchema(context)),
		chargeEffect: v.optional(EffectFieldSchema(context)),
		smokeEffect: v.optional(EffectFieldSchema(context)),
		shootSound: v.optional(SoundHjsonSchema),
		hitSound: v.optional(SoundHjsonSchema),
		despawnSound: v.optional(SoundHjsonSchema),
		hitSoundPitch: v.optional(v.number(), 1),
		hitSoundPitchRange: v.optional(v.number(), 0.1),
		hitSoundVolume: v.optional(v.number(), 1),
		inaccuracy: v.optional(v.number(), 0),
		ammoMultiplier: v.optional(v.number(), 2),
		reloadMultiplier: v.optional(v.number(), 1),
		buildingDamageMultiplier: v.optional(v.number(), 1),
		shieldDamageMultiplier: v.optional(v.number(), 1),
		recoil: v.optional(v.number(), 0),
		killShooter: v.optional(v.boolean(), false),
		instantDisappear: v.optional(v.boolean(), false),
		splashDamage: v.optional(v.number(), 0),
		scaledSplashDamage: v.optional(v.boolean(), false),
		knockback: v.optional(v.number(), 0),
		impact: v.optional(v.boolean(), false),
		status: v.optional(StatusFieldSchema(context)),
		statusDuration: v.optional(v.number(), 480),
		targetBlocks: v.optional(v.boolean(), true),
		targetMissiles: v.optional(v.boolean(), true),
		collidesTiles: v.optional(v.boolean(), true),
		collidesTeam: v.optional(v.boolean(), false),
		collidesAir: v.optional(v.boolean(), true),
		collidesGround: v.optional(v.boolean(), true),
		collides: v.optional(v.boolean(), true),
		collideFloor: v.optional(v.boolean(), false),
		collideTerrain: v.optional(v.boolean(), false),
		keepVelocity: v.optional(v.boolean(), true),
		scaleKeepVelocity: v.optional(v.boolean(), false),
		scaleLife: v.optional(v.boolean(), false),
		hittable: v.optional(v.boolean(), true),
		reflectable: v.optional(v.boolean(), true),
		absorbable: v.optional(v.boolean(), true),
		ignoreSpawnAngle: v.optional(v.boolean(), false),
		createChance: v.optional(v.number(), 1),
		maxRange: v.optional(v.number(), -1),
		rangeOverride: v.optional(v.number(), -1),
		rangeChange: v.optional(v.number(), 0),
		extraRangeMargin: v.optional(v.number(), 0),
		range: v.optional(v.number(), 0),
		minRangeChange: v.optional(v.number(), 0),
		healPercent: v.optional(v.number(), 0),
		healAmount: v.optional(v.number(), 0),
		healSound: v.optional(SoundHjsonSchema),
		healSoundVolume: v.optional(v.number(), 0.9),
		lifesteal: v.optional(v.number(), 0),
		makeFire: v.optional(v.boolean(), false),
		hitUnder: v.optional(v.boolean(), false),
		despawnHit: v.optional(v.boolean(), false),
		fragOnHit: v.optional(v.boolean(), true),
		fragOnDespawn: v.optional(v.boolean(), true),
		fragOnAbsorb: v.optional(v.boolean(), true),
		pierceArmor: v.optional(v.boolean(), false),
		armorMultiplier: v.optional(v.number(), 1),
		blockArmorMultiplier: v.optional(v.number(), 1),
		sticky: v.optional(v.boolean(), false),
		stickyExtraLifetime: v.optional(v.number(), 0),
		setDefaults: v.optional(v.boolean(), true),
		hitShake: v.optional(v.number(), 0),
		despawnShake: v.optional(v.number(), 0),
		fragBullet: v.optional(BulletHjsonSchema(context)),
		delayFrags: v.optional(v.boolean(), false),
		fragRandomSpread: v.optional(v.number(), 360),
		fragSpread: v.optional(v.number(), 0),
		fragAngle: v.optional(v.number(), 0),
		fragBullets: v.optional(v.number(), 9),
		fragVelocityMin: v.optional(v.number(), 0.2),
		fragVelocityMax: v.optional(v.number(), 1),
		fragLifeMin: v.optional(v.number(), 1),
		fragLifeMax: v.optional(v.number(), 1),
		fragOffsetMin: v.optional(v.number(), 1),
		fragOffsetMax: v.optional(v.number(), 7),
		pierceFragCap: v.optional(v.number(), -1),
		intervalBullet: v.optional(BulletHjsonSchema(context)),
		bulletInterval: v.optional(v.number(), 20),
		intervalBullets: v.optional(v.number(), 1),
		intervalRandomSpread: v.optional(v.number(), 360),
		intervalSpread: v.optional(v.number(), 0),
		intervalAngle: v.optional(v.number(), 0),
		intervalDelay: v.optional(v.number(), -1),
		underwater: v.optional(v.boolean(), false),
		hitColor: v.optional(MindustryHexColorSchema),
		healColor: v.optional(MindustryHexColorSchema),
		healEffect: v.optional(EffectFieldSchema(context)),
		spawnBullets: v.optional(v.array(BulletHjsonSchema(context)), []),
		showStats: v.optional(v.boolean(), false),
		spawnBulletRandomSpread: v.optional(v.number(), 0),
		spawnUnit: v.optional(UnitFieldSchema(context)),
		despawnUnit: v.optional(UnitFieldSchema(context)),
		despawnUnitChance: v.optional(v.number(), 1),
		despawnUnitCount: v.optional(v.number(), 1),
		despawnUnitRadius: v.optional(v.number(), 0.1),
		faceOutwards: v.optional(v.boolean(), false),
		parts: v.optional(v.array(PartHjsonSchema(context)), []),
		trailColor: v.optional(MindustryHexColorSchema),
		trailChance: v.optional(v.number(), -0.0001),
		trailInterval: v.optional(v.number(), 0),
		trailMinVelocity: v.optional(v.number(), 0),
		trailEffect: v.optional(EffectFieldSchema(context)),
		trailSpread: v.optional(v.number(), 0),
		trailParam: v.optional(v.number(), 2),
		trailRotation: v.optional(v.boolean(), false),
		trailInterp: v.optional(v.picklist(Interps), "one"),
		trailLength: v.optional(v.number(), -1),
		trailWidth: v.optional(v.number(), 2),
		circleShooter: v.optional(v.boolean(), false),
		circleShooterRadius: v.optional(v.number(), 13),
		circleShooterRadiusSmooth: v.optional(v.number(), 10),
		circleShooterRotateSpeed: v.optional(v.number(), 0.3),
		splashDamageRadius: v.optional(v.number(), -1),
		splashDamagePierce: v.optional(v.boolean(), false),
		incendAmount: v.optional(v.number(), 0),
		incendSpread: v.optional(v.number(), 8),
		incendChance: v.optional(v.number(), 1),
		homingPower: v.optional(v.number(), 0),
		homingRange: v.optional(v.number(), 50),
		homingDelay: v.optional(v.number(), -1),
		followAimSpeed: v.optional(v.number(), 0),
		suppressionRange: v.optional(v.number(), -1),
		suppressionDuration: v.optional(v.number(), 480),
		suppressionEffectChance: v.optional(v.number(), 50),
		suppressColor: v.optional(MindustryHexColorSchema),
		lightningColor: v.optional(MindustryHexColorSchema),
		puddles: v.optional(v.number(), 0),
		puddleRange: v.optional(v.number(), 0),
		puddleAmount: v.optional(v.number(), 5),
		puddleLiquid: v.optional(LiquidFieldSchema(context)),
		lightning: v.optional(v.number(), 0),
		lightningLength: v.optional(v.number(), 5),
		lightningLengthRand: v.optional(v.number(), 0),
		lightningDamage: v.optional(v.number(), -1),
		lightningCone: v.optional(v.number(), 360),
		lightningAngle: v.optional(v.number(), 0),
		lightningType: v.optional(BulletHjsonSchema(context)),
		weaveScale: v.optional(v.number(), 1),
		weaveMag: v.optional(v.number(), 0),
		weaveRandom: v.optional(v.boolean(), true),
		rotateSpeed: v.optional(v.number(), 0),
		displayAmmoMultiplier: v.optional(v.boolean(), true),
		statLiquidConsumed: v.optional(v.number(), 0),
		lightRadius: v.optional(v.number(), -1),
		lightOpacity: v.optional(v.number(), 0.3),
		lightColor: v.optional(MindustryHexColorSchema),

		backColor: v.optional(MindustryHexColorSchema),
		frontColor: v.optional(MindustryHexColorSchema),
		width: v.optional(v.number(), 5),
		height: v.optional(v.number(), 7),
		shrinkX: v.optional(v.number(), 0),
		shrinkY: v.optional(v.number(), 0.5),
		spin: v.optional(v.number(), 0),
		backSprite: v.optional(v.string()),
		shrinkInterp: v.optional(v.picklist(Interps), "linear"),
	});
};

const classSchemaMap: Record<BulletClass, SchemaFn<BulletObjectSchema>> = {
	ArtilleryBulletType: (_context) =>
		v.object({
			trailMult: v.optional(v.number(), 1),
			trailSize: v.optional(v.number(), 4),
		}),
	BasicBulletType: (_context) => v.object({}),
	BombBulletType: (_context) => v.object({}),
	BulletType: (_context) => v.object({}),
	ContinuousBulletType: (_context) =>
		v.object({
			length: v.optional(v.number(), 220),
			damageInterval: v.optional(v.number(), 5),
			continuous: v.optional(v.boolean(), true),
		}),
	ContinuousFlameBulletType: (_context) => v.object({}),
	ContinuousLaserBulletType: (_context) => v.object({}),
	EmpBulletType: (context) =>
		v.object({
			radius: v.optional(v.number(), 100),
			timeIncrease: v.optional(v.number(), 2.5),
			timeDuration: v.optional(v.number(), 600),
			unitDamageScl: v.optional(v.number(), 0.7),
			hitPowerEffect: EffectFieldSchema(context),
			hitUnits: v.optional(v.boolean(), true),
			powerDamageScl: v.optional(v.number(), 2),
			powerSclDecrease: v.optional(v.number(), 0.2),
			chainEffect: EffectFieldSchema(context),
			applyEffect: EffectFieldSchema(context),
		}),
	EmptyBulletType: (_context) => v.object({}),
	ExplosionBulletType: (_context) => v.object({}),
	FireBulletType: (_context) => v.object({}),
	FlakBulletType: (_context) => v.object({}),
	InterceptorBulletType: (_context) => v.object({}),
	LaserBoltBulletType: (_context) => v.object({}),
	LaserBulletType: (_context) =>
		v.object({
			length: v.optional(v.number(), 160),
			width: v.optional(v.number(), 15),
			lengthFalloff: v.optional(v.number(), 0.5),
			sideLength: v.optional(v.number(), 29),
			sideWidth: v.optional(v.number(), 0.7),
			lightningSpacing: v.optional(v.number(), -1),
		}),
	LightningBulletType: (_context) => v.object({}),
	LiquidBulletType: (_context) =>
		v.object({
			puddleSize: v.optional(v.number(), 6),
			orbSize: v.optional(v.number(), 3),
			boilTime: v.optional(v.number(), 5),
		}),
	MassDriverBolt: (_context) => v.object({}),
	MissileBulletType: (_context) => v.object({}),
	MultiBulletType: (context) =>
		v.object({
			bullets: v.array(BulletHjsonSchema(context)),
			repeat: v.optional(v.number(), 1),
		}),
	PointBulletType: (_context) => v.object({}),
	PointLaserBulletType: (_context) =>
		v.object({
			oscScl: v.optional(v.number(), 2),
			oscMag: v.optional(v.number(), 0.3),
			damageInterval: v.optional(v.number(), 5),
		}),
	RailBulletType: (_context) =>
		v.object({
			length: v.optional(v.number(), 100),
			pointEffectSpace: v.optional(v.number(), 20),
		}),
	SapBulletType: (_context) =>
		v.object({
			length: v.optional(v.number(), 100),
			sapStrength: v.optional(v.number(), 0.5),
			color: v.optional(MindustryHexColorSchema),
		}),
	ShrapnelBulletType: (_context) =>
		v.object({
			length: v.optional(v.number(), 100),
			width: v.optional(v.number(), 20),
			serrations: v.optional(v.number(), 7),
			serrationSpacing: v.optional(v.number(), 8),
		}),
	SpaceLiquidBulletType: (_context) => v.object({}),
};

export const BulletHjsonSchema: SchemaFn = (context) => {
	return v.lazy((input) => {
		if (input && typeof input === "object" && "type" in input) {
			const type = input["type"] as string;

			if (classSchemaMap[type as BulletClass]) {
				const schema = classSchemaMap[type as BulletClass];
				return v.pipe(v.object({ ...createBulletBaseObjectSchema(context).entries, ...schema(context).entries }), v.metadata(metadata));
			}
		}

		return v.pipe(createBulletBaseObjectSchema(context), v.metadata(metadata));
	});
};
