import * as v from "valibot";
import { Envs, EnvSchema, MindustryHexColorSchema, SoundHjsonSchema, type SchemaFn } from "./base";
import { AbilityHjsonSchema } from "./ability";
import { WeaponHjsonSchema } from "./weapon";
import { StatusStringSchema } from "./status";
import { EffectHjsonSchema } from "./effect";
import { PartHjsonSchema } from "./part";
import { EngineHjsonSchema } from "./engine";
import { lazyArray } from "./lazy-array";

export const UnitHjsonSchema: SchemaFn = (value, context) =>
	v.object({
		envRequired: v.optional(EnvSchema, 0),
		envEnabled: v.optional(EnvSchema, Envs.terrestrial),
		envDisabled: v.optional(EnvSchema, Envs.scorching),
		speed: v.optional(v.number(), 1.1),
		boostMultiplier: v.optional(v.number(), 1),
		floorMultiplier: v.optional(v.number(), 1),
		rotateSpeed: v.optional(v.number(), 5),
		baseRotateSpeed: v.optional(v.number(), 5),
		drag: v.optional(v.number(), 0.3),
		accel: v.optional(v.number(), 0.5),
		hitSize: v.optional(v.number(), 6),
		deathShake: v.optional(v.number(), -1),
		stepShake: v.optional(v.number(), -1),
		rippleScale: v.optional(v.number(), 1),
		riseSpeed: v.optional(v.number(), 0.08),
		descentSpeed: v.optional(v.number(), 0.08),
		fallSpeed: v.optional(v.number(), 0.018),
		missileAccelTime: v.optional(v.number(), 0),
		health: v.optional(v.number(), 200),
		armor: v.optional(v.number(), 0),
		range: v.optional(v.number(), -1),
		maxRange: v.optional(v.number(), -1),
		mineRange: v.optional(v.number(), 70),
		buildRange: v.optional(v.number()),
		circleTargetRadius: v.optional(v.number(), 80),
		crashDamageMultiplier: v.optional(v.number(), 1),
		wreckHealthMultiplier: v.optional(v.number(), 0.25),
		dpsEstimate: v.optional(v.number(), -1),
		clipSize: v.optional(v.number(), -1),
		drownTimeMultiplier: v.optional(v.number(), 1),
		strafePenalty: v.optional(v.number(), 0.5),
		researchCostMultiplier: v.optional(v.number(), 50),

		groundLayer: v.optional(v.number()),
		flyingLayer: v.optional(v.number(), -1),
		payloadCapacity: v.optional(v.number(), 8),
		buildSpeed: v.optional(v.number(), -1),
		aimDst: v.optional(v.number(), -1),
		buildBeamOffset: v.optional(v.number(), 3.8),
		mineBeamOffset: v.optional(v.number()),
		targetPriority: v.optional(v.number(), 0),
		shadowElevation: v.optional(v.number(), -1),
		shadowElevationScl: v.optional(v.number(), 1),
		engineOffset: v.optional(v.number(), 5),
		engineSize: v.optional(v.number(), 2.5),
		engineLayer: v.optional(v.number(), -1),
		itemOffsetY: v.optional(v.number(), 3),
		lightRadius: v.optional(v.number(), -1),
		lightOpacity: v.optional(v.number(), 0.6),
		softShadowScl: v.optional(v.number(), 1),
		fogRadius: v.optional(v.number(), -1),

		waveTrailX: v.optional(v.number(), 4),
		waveTrailY: v.optional(v.number(), -3),
		trailScl: v.optional(v.number(), 1),

		isEnemy: v.optional(v.boolean(), true),
		flying: v.optional(v.boolean(), false),
		wobble: v.optional(v.boolean(), true),
		targetAir: v.optional(v.boolean(), true),
		targetGround: v.optional(v.boolean(), true),
		faceTarget: v.optional(v.boolean(), true),
		circleTarget: v.optional(v.boolean(), false),
		autoDropBombs: v.optional(v.boolean(), false),
		targetBuildingsMobile: v.optional(v.boolean(), true),
		canBoost: v.optional(v.boolean(), false),
		boostWhenBuilding: v.optional(v.boolean(), true),
		boostWhenMining: v.optional(v.boolean(), true),
		logicControllable: v.optional(v.boolean(), true),
		playerControllable: v.optional(v.boolean(), true),
		controlSelectGlobal: v.optional(v.boolean(), true),
		allowedInPayloads: v.optional(v.boolean(), true),
		hittable: v.optional(v.boolean(), true),
		killable: v.optional(v.boolean(), true),
		targetable: v.optional(v.boolean(), true),
		vulnerableWithPayloads: v.optional(v.boolean(), false),
		pickupUnits: v.optional(v.boolean(), true),
		physics: v.optional(v.boolean(), true),
		canDrown: v.optional(v.boolean(), true),
		useUnitCap: v.optional(v.boolean(), true),
		coreUnitDock: v.optional(v.boolean(), false),
		createWreck: v.optional(v.boolean(), true),
		createScorch: v.optional(v.boolean(), true),
		lowAltitude: v.optional(v.boolean(), false),
		rotateToBuilding: v.optional(v.boolean(), true),
		allowLegStep: v.optional(v.boolean(), false),
		legPhysicsLayer: v.optional(v.boolean(), true),
		hovering: v.optional(v.boolean(), false),
		omniMovement: v.optional(v.boolean(), true),
		rotateMoveFirst: v.optional(v.boolean(), false),
		healFlash: v.optional(v.boolean(), true),
		canHeal: v.optional(v.boolean(), false),
		singleTarget: v.optional(v.boolean(), false),
		forceMultiTarget: v.optional(v.boolean(), false),
		canAttack: v.optional(v.boolean(), true),
		hidden: v.optional(v.boolean(), false),
		internal: v.optional(v.boolean(), false),
		internalGenerateSprites: v.optional(v.boolean(), false),
		bounded: v.optional(v.boolean(), true),
		naval: v.optional(v.boolean(), false),
		autoFindTarget: v.optional(v.boolean(), true),
		targetUnderBlocks: v.optional(v.boolean(), true),
		alwaysShootWhenMoving: v.optional(v.boolean(), false),

		hoverable: v.optional(v.boolean(), true),
		alwaysCreateOutline: v.optional(v.boolean(), false),
		generateFullIcon: v.optional(v.boolean(), true),
		squareShape: v.optional(v.boolean(), false),
		drawBuildBeam: v.optional(v.boolean(), true),
		drawMineBeam: v.optional(v.boolean(), true),
		drawCell: v.optional(v.boolean(), true),
		drawItems: v.optional(v.boolean(), true),
		drawShields: v.optional(v.boolean(), true),
		drawBody: v.optional(v.boolean(), true),
		drawSoftShadow: v.optional(v.boolean(), true),
		drawMinimap: v.optional(v.boolean(), true),

		deathSoundVolume: v.optional(v.number(), 1),
		wreckSoundVolume: v.optional(v.number(), 1),
		loopSoundVolume: v.optional(v.number(), 0.5),
		stepSoundVolume: v.optional(v.number(), 0.5),
		stepSoundPitch: v.optional(v.number(), 1),
		stepSoundPitchRange: v.optional(v.number(), 0.1),
		moveSoundVolume: v.optional(v.number(), 1),
		moveSoundPitchMin: v.optional(v.number(), 1),
		moveSoundPitchMax: v.optional(v.number(), 1),
		tankMoveVolume: v.optional(v.number(), 0.5),

		useEngineElevation: v.optional(v.boolean(), true),

		trailLength: v.optional(v.number(), 0),

		flowfieldPathType: v.optional(v.number(), -1),
		pathCostId: v.optional(v.number()),

		allowChangeCommands: v.optional(v.boolean(), true),

		outlineRadius: v.optional(v.number(), 3),
		outlines: v.optional(v.boolean(), true),

		itemCapacity: v.optional(v.number(), -1),
		ammoCapacity: v.optional(v.number(), 1),

		mineTier: v.optional(v.number(), -1),
		mineSpeed: v.optional(v.number(), 1),
		mineWalls: v.optional(v.boolean(), false),
		mineFloor: v.optional(v.boolean(), true),
		mineHardnessScaling: v.optional(v.boolean(), true),
		mineSoundVolume: v.optional(v.number(), 0.6),

		// LEG UNITS

		legCount: v.optional(v.number(), 4),
		legGroupSize: v.optional(v.number(), 2),

		legLength: v.optional(v.number(), 10),
		legSpeed: v.optional(v.number(), 0.1),
		legForwardScl: v.optional(v.number(), 1),
		legBaseOffset: v.optional(v.number(), 0),
		legMoveSpace: v.optional(v.number(), 1),
		legExtension: v.optional(v.number(), 0),
		legPairOffset: v.optional(v.number(), 0),
		legLengthScl: v.optional(v.number(), 1),
		legStraightLength: v.optional(v.number(), 1),
		legMaxLength: v.optional(v.number(), 1.75),
		legMinLength: v.optional(v.number(), 0),
		legSplashDamage: v.optional(v.number(), 0),
		legSplashRange: v.optional(v.number(), 5),
		baseLegStraightness: v.optional(v.number(), 0),
		legStraightness: v.optional(v.number(), 0),

		legBaseUnder: v.optional(v.boolean(), false),
		lockLegBase: v.optional(v.boolean(), false),
		legContinuousMove: v.optional(v.boolean()),
		flipBackLegs: v.optional(v.boolean(), true),
		flipLegSide: v.optional(v.boolean(), false),
		emitWalkSound: v.optional(v.boolean(), true),
		emitWalkEffect: v.optional(v.boolean(), true),

		// MECH UNITS

		mechLandShake: v.optional(v.number(), 0),
		mechSideSway: v.optional(v.number(), 0.54),
		mechFrontSway: v.optional(v.number(), 0.1),
		mechStride: v.optional(v.number(), -1),
		mechStepParticles: v.optional(v.boolean(), false),

		// TANK UNITS

		treadFrames: v.optional(v.number(), 18),
		treadPullOffset: v.optional(v.number(), 0),
		crushFragile: v.optional(v.boolean(), false),

		// SEGMENTED / CRAWL UNITS

		segments: v.optional(v.number(), 0),
		segmentUnits: v.optional(v.number(), 1),
		segmentLayerOrder: v.optional(v.boolean(), true),

		segmentMag: v.optional(v.number(), 2),
		segmentScl: v.optional(v.number(), 4),
		segmentPhase: v.optional(v.number(), 5),
		segmentRotSpeed: v.optional(v.number(), 1),
		segmentMaxRot: v.optional(v.number(), 30),
		segmentSpacing: v.optional(v.number(), -1),
		segmentRotationRange: v.optional(v.number(), 80),
		crawlSlowdown: v.optional(v.number(), 0.5),
		crushDamage: v.optional(v.number(), 0),
		crawlSlowdownFrac: v.optional(v.number(), 0.55),

		// MISSILE UNITS

		lifetime: v.optional(v.number(), 60 * 5),
		homingDelay: v.optional(v.number(), 10),

		abilities: v.optional(
			lazyArray((index) => AbilityHjsonSchema(value.get("abilities").get(index), context)),
			[],
		),
		weapons: v.optional(
			lazyArray((index) => WeaponHjsonSchema(value.get("weapons").get(index), context)),
			[],
		),
		immunities: v.optional(
			lazyArray((index) => StatusStringSchema(value.get("immunities").get(index), context)),
			[],
		),
		healColor: v.optional(MindustryHexColorSchema),
		lightColor: v.optional(MindustryHexColorSchema),
		shieldColor: v.optional(MindustryHexColorSchema),

		deathSound: v.optional(SoundHjsonSchema),
		wreckSound: v.optional(SoundHjsonSchema),
		loopSound: v.optional(SoundHjsonSchema),
		stepSound: v.optional(SoundHjsonSchema),
		tankMoveSound: v.optional(SoundHjsonSchema),
		moveSound: v.optional(SoundHjsonSchema),
		fallEffect: v.optional(EffectHjsonSchema(value, context)),
		fallEngineEffect: v.optional(EffectHjsonSchema(value, context)),
		deathExplosionEffect: v.optional(EffectHjsonSchema(value, context)),
		treadEffect: v.optional(EffectHjsonSchema(value, context)),
		parts: v.optional(
			lazyArray((index) => PartHjsonSchema(value.get("parts").get(index), context)),
			[],
		),
		engines: v.optional(
			lazyArray((index) => EngineHjsonSchema(value.get("engines").get(index), context)),
			[],
		),
		engineColor: v.optional(MindustryHexColorSchema),
		engineColorInner: v.optional(MindustryHexColorSchema),
		trailColor: v.optional(MindustryHexColorSchema),
		outlineColor: v.optional(MindustryHexColorSchema),
		mineSound: v.optional(SoundHjsonSchema),
		mechLegColor: v.optional(MindustryHexColorSchema),
	});
